Add all_data_read judgment to S3TrivialReader
ByConity/ByConity pull request #1033
Opened 2024-01-08 13:16 UTC by Hzc492

### Changelog category :
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- fix issue  #851

Current `S3TrivialReader` sends another read request even after completely reading an AWS S3 file, causing a HTTP exception  `Response status: 416, Requested Range Not Satisfiable`. This PR adds a boolean variable `all_data_read` and sets it to true when meeting `stream.eof()`. When `all_data_read=true`, `S3TrivialReader::read` just returns 0 instead of sending a request.

2024-01-08 13:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ByConity/ByConity?pullRequest=1033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=1033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=1033) it.</sub>

2024-01-09 03:41 UTC, dmthuc commented
Hi @Michael-LinYu , please help to review this MR

2024-01-09 04:24 UTC, Alima777 requested changes

2024-01-09 04:24 UTC, Alima777 commented on src/IO/S3RemoteFSReader.cpp
>      SCOPE_EXIT_SAFE({ S3::resetSessionIfNeeded(all_data_read, result); });
You can use another parameter to represent 'Stream is end'. 
`all_data_read` here is used to reset session. If data in the http request is not read completely, we have to reset session, otherwise session will be reused and read previous data, which will lead to an exception.

2024-01-09 06:34 UTC, Hzc492 commented on src/IO/S3RemoteFSReader.cpp
>      SCOPE_EXIT_SAFE({ S3::resetSessionIfNeeded(all_data_read, result); });
Thanks for comments. Modified, leaving `all_data_read` unchanged and using `completed_` instead.

2024-01-09 09:09 UTC, Alima777 requested changes

2024-01-09 09:09 UTC, Alima777 commented on src/IO/S3RemoteFSReader.cpp
> +            completed_ = true;
Thanks for your quick fix.
But I think `finished` may be better :D. And set it true at code line 79?

2024-01-09 10:57 UTC, Hzc492 commented on src/IO/S3RemoteFSReader.cpp
> +            completed_ = true;
thanks, modified~

2024-01-09 13:01 UTC, Alima777 approved these changes
LGTM

2024-01-09 13:12 UTC, Michael-LinYu approved these changes

2024-01-10 02:22 UTC, dmthuc commented
Hi @Hzc492 , can you resolve the CLA check by adding `hzc` email into your github account
![image](https://github.com/ByConity/ByConity/assets/13962605/724e784f-16eb-451b-9ea8-979c67b3fd39)

2024-01-10 03:12 UTC, Hzc492 commented
> Hi @Hzc492 , can you resolve the CLA check by adding `hzc` email into your github account ![image](https://private-user-images.githubusercontent.com/13962605/295408822-724e784f-16eb-451b-9ea8-979c67b3fd39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTYzNjYsIm5iZiI6MTcwNDg1NjA2NiwicGF0aCI6Ii8xMzk2MjYwNS8yOTU0MDg4MjItNzI0ZTc4NGYtMTZlYi00NTFiLTllYTgtOTc5YzY3YjNmZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAzMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YzBkZGIwMDZiMjQ0YjMwYzNkODJiZTQ5NmJjYjMzZWQ1ZTUyNDA0ZjljZDdmNmVkM2EwYTViZTE3NGU1MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qr2T-xGTVGDdKmkapf9ACnpxjH4sF25FbBoNZDD8Ock)

Thanks for reminder, removed `hzc` by rebase, sorry for the trouble.

2024-01-10 07:15 UTC, merged