replace ListObjects by HeadObject when inserting data to DiskByteS3
ByConity/ByConity pull request #1068
Opened 2024-01-18 08:41 UTC by Hzc492

### Changelog category :
- Improvement

This PR tries to fix  #1067, by using `AWS::S3::HeadObject` instead of `AWS::S3::ListObjects`.
It seems currently `ListObjects` is called 2 times when executing `insert ... into ...`:
1. `MergeTreeCNCHDataDumper::dumpTempPart` checks if there are any files in directory `new_part_rel_path`
2. `DiskByteS3::writeFile` checks if the file exists

Modifies on `S3Util::exists` only fix the second. 
To fix the first, I static_cast `disk` to `DiskByteS3` and call the newly added `existsFile` method. It doesn't look elegant enough, so suggestions are welcome.

2024-01-19 02:53 UTC, dmthuc commented
Please rebase to the latest to fix CI issue

2024-01-31 07:17 UTC, Alima777 requested changes

2024-01-31 07:17 UTC, Alima777 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
Why not just change the implementation of exists() method of DiskByteS3?

2024-01-31 07:17 UTC, Alima777 commented on src/Disks/DiskByteS3.h
> +    bool existsFile(const String & path_file) const;
It's not a big problem, but `isFileExist` is better

2024-01-31 07:46 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
The current `DiskByteS3::exists()` method returns true if there are any files prefixed with the given path, so inputs such as folders are valid. In order to use `HeadObject()` method of AWS S3, my `isFileExist()` method only determines if an exact file exists. I was afraid to change the semantics of the current `exists()`, so I added the `isFileExist()` method. Alternatively, We could modify current `exists()` to check if the input path ends with `"data"` to determine whether to use `HeadObject()` or `ListObjects()`, but it doesn't seem elegant. Suggestions are welcome.

> Why not just change the implementation of exists() method of DiskByteS3?

2024-01-31 08:41 UTC, Alima777 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
I got your point. But since `isDirectoryExist` is judged here, are you sure that join `/data` to path and check the object `path/data` is the same semantics?

2024-01-31 09:26 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
Indeed, semantically they are not the same. If DiskByteS3 stops guaranteeing only one data file per folder, this could really lead to problems. So it would be better to remove this part of modifications?

2024-01-31 11:50 UTC, Alima777 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
I think just optimize `exists()` in S3Common.cpp is good enough. Let's just keep it the same here. What do you think?

2024-01-31 14:40 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
> +    switch(disk->getType())
Great, I agree. Modified.

2024-02-01 02:38 UTC, Alima777 approved these changes

2024-02-01 02:47 UTC, merged

2024-02-23 02:43 UTC, skyoct commented
@Alima777 @Hzc492 
On this PR basis, there will still be many list requests.