Reduction in the use of ListObject in DiskByteS3
ByConity/ByConity pull request #1249
Opened 2024-02-28 07:51 UTC by Hzc492

This PR tries to fix issue #1243.

AWS S3 ListObject is used in `DiskByteS3::exists` and `DiskByteS3::removeDirectory/Recursive`, which should be avoided. Instead of changing the semantics of the current DiskByteS3 interfaces, I add new interfaces (`fileExists` and `removePart`) to DiskByteS3. The upper-level (`MergeTreeCNCHDataDumper` and `MergeTreeDataPartCNCH`) checks if the target disk is DiskByteS3, and if so, they calls these new interfaces.

Currently, there is only one file `"data"` in each S3 part. So I only operates on this file. If there are multiple files in the future, something will go wrong. So I add a warning log in `DiskByteS3::writeFile` function.

**NEED ATTENTION**：I modifid `DiskByteS3::removeFileIfExists`, because I don't think its original implementation was correct. When the file does not exist, the original implementation will throw exception.

2024-03-01 06:53 UTC, smmsmm1988 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.h
DeleteBitmapMeta::removeFile() has to be taken into consideration as well, because bitmap operations also reach S3

2024-03-07 01:11 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.h
modified

2024-03-07 02:02 UTC, smmsmm1988 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.h
> +    static bool fileExists(const DB::DiskPtr &disk, const String &data_file_path);
May we can avoid duplicated definition of fileExists in two classes and just define and implement it in IDisk?

2024-03-07 06:01 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.h
> +    static bool fileExists(const DB::DiskPtr &disk, const String &data_file_path);
modified, move fileExists to IDisk

2024-03-07 06:24 UTC, gaodayue requested changes

2024-03-07 06:24 UTC, gaodayue commented on src/Disks/IDisk.h
> +    bool fileExists(const String & file_path);
virtual

2024-03-07 06:24 UTC, gaodayue commented on src/Disks/IDisk.cpp
> +bool IDisk::fileExists(const String & file_path)
this is ugly. the default impl can invoke `exists` directly, and DiskByteS3 can override `fileExist`

2024-03-07 06:24 UTC, gaodayue commented on src/Disks/DiskByteS3.h
> +    static constexpr auto BITMAP_FILE = ".bitmap";
DiskByteS3 should not be aware of this business concept

2024-03-07 06:24 UTC, gaodayue commented on src/Disks/DiskByteS3.cpp
> +    if (fileExists(path))
any reason to change this? I think current impl is better (only one http request)

2024-03-07 06:24 UTC, gaodayue commented on src/Disks/DiskByteS3.cpp
> +    if (!path.ends_with(String("/") + DATA_FILE) && !(path.starts_with(BITMAP_DIR) && path.ends_with(BITMAP_FILE)))
remove these checks, this should be guaranteed by upper layer

2024-03-07 06:38 UTC, smmsmm1988 commented on src/Disks/IDisk.cpp
> +bool IDisk::fileExists(const String & file_path)
How about reusing virtual interface exists and DiskByteS3 gives its own implementation?

2024-03-07 06:48 UTC, smmsmm1988 commented on src/Disks/DiskByteS3.h
> +    void removePart(const String & part_path);
I think it's acceptable if class DiskByteS3 has its own methods for specific operations, as ListObject and HeadObject are only S3-related. The upper layer knows when to call these methods.

2024-03-07 08:54 UTC, Hzc492 commented on src/Disks/DiskByteS3.h
> +    void removePart(const String & part_path);
I temporarily moved these part operations to the upper layer...  Maybe in the future it would be nice to have a new specialized class that manages files on S3 and is responsible for communicating between the upper layer and DiskByteS3?

2024-03-07 08:57 UTC, Hzc492 commented on src/Disks/IDisk.cpp
> +bool IDisk::fileExists(const String & file_path)
modified, making IDisk::fileExists virtual and overriding it in DiskByteS3

2024-03-07 08:59 UTC, Hzc492 commented on src/Disks/DiskByteS3.cpp
> +    if (!path.ends_with(String("/") + DATA_FILE) && !(path.starts_with(BITMAP_DIR) && path.ends_with(BITMAP_FILE)))
modifed according to comments

2024-03-08 06:33 UTC, gaodayue requested changes

2024-03-08 06:33 UTC, gaodayue commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> +    if (!volume->getDisk()->fileExists(data_file_path))
如果文件不存在，上面的getFileSize应该就会报错？

2024-03-08 06:33 UTC, gaodayue commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> -        if (!disk->exists(path_on_disk)) {
part目录下只有data文件。由于s3没有目录，对于S3 disk可以跳过上面的`removeDirectory`

2024-03-08 06:33 UTC, gaodayue commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> +        if (!volume->getDisk()->fileExists(part_path))
函数开头判断过fileExists了，可以去掉这个判断

2024-03-08 06:40 UTC, Alima777 approved these changes
LGTM

2024-03-11 05:34 UTC, Hzc492 commented on src/Storages/MergeTree/DeleteBitmapMeta.cpp
> +        if (likely(disk->fileExists(rel_file_path)))
已替换

2024-03-11 05:34 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> +    if (!volume->getDisk()->fileExists(data_file_path))
确实，已将该if判断删除

2024-03-11 05:34 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> -        if (!disk->exists(path_on_disk)) {
已更改

2024-03-11 05:35 UTC, Hzc492 commented on src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
> +        if (!volume->getDisk()->fileExists(part_path))
已删除

2024-03-14 12:55 UTC, merged