Create HDFS_installation_zh.md
ByConity/ByConity pull request #136
Opened 2023-03-08 04:04 UTC by xxisxuxu

I hereby agree to the terms of the CLA available at: [placeholder]

Changelog category (leave one):

- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Add Chinese doc of Create HDFS_installation.

Detailed description / Documentation draft:

...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

2023-03-08 04:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ByConity/ByConity?pullRequest=136) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=136) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=136) it.</sub>

2023-03-08 04:06 UTC, xxisxuxu commented
@kevinthfang please review it.

2023-03-08 05:38 UTC, kevinthfang requested changes

2023-03-08 05:38 UTC, kevinthfang commented on docker/executable_wrapper/HDFS_installation_zh.md
> +在本指南中，我将在 3 台机器上设置 HDFS，其中 1 台机器用于名称节点（namenode），另外 2 台机器用于数据节点（datanode）。 我参考了官方文档 SingleCluster 和 ClusterSetup。 我将安装 HDFS 版本 3.3.4，因此我需要 java-8，因为这是 Hadoop 推荐的 Java 版本。
专有名字不用翻译，比如名称节点（namenode），下同

2023-03-08 05:38 UTC, kevinthfang commented on docker/executable_wrapper/HDFS_installation_zh.md
> +在本指南中，我将在 3 台机器上设置 HDFS，其中 1 台机器用于名称节点（namenode），另外 2 台机器用于数据节点（datanode）。 我参考了官方文档 SingleCluster 和 ClusterSetup。 我将安装 HDFS 版本 3.3.4，因此我需要 java-8，因为这是 Hadoop 推荐的 Java 版本。
“我”改成”这里“比较好，下同，‘我们’可以保留

2023-03-08 05:38 UTC, kevinthfang commented on docker/executable_wrapper/HDFS_installation_zh.md
> +这就是 namenode 的配置。 现在对于你需要部署 datanode 的那两个节点，创建一个目录来存储 datanode 运行时数据
换行

2023-03-08 05:38 UTC, kevinthfang commented on docker/executable_wrapper/HDFS_installation_zh.md
> +然后到另外两台datanode机器，到 hadoop 分布，用下面这个命令启动 data node
‘分布’改成文件夹下同

2023-03-10 07:16 UTC, xxisxuxu commented on docker/executable_wrapper/HDFS_installation_zh.md
> +在本指南中，我将在 3 台机器上设置 HDFS，其中 1 台机器用于名称节点（namenode），另外 2 台机器用于数据节点（datanode）。 我参考了官方文档 SingleCluster 和 ClusterSetup。 我将安装 HDFS 版本 3.3.4，因此我需要 java-8，因为这是 Hadoop 推荐的 Java 版本。
> 专有名字不用翻译，比如名称节点（namenode），下同

already edited.

2023-03-10 07:16 UTC, xxisxuxu commented on docker/executable_wrapper/HDFS_installation_zh.md
> +在本指南中，我将在 3 台机器上设置 HDFS，其中 1 台机器用于名称节点（namenode），另外 2 台机器用于数据节点（datanode）。 我参考了官方文档 SingleCluster 和 ClusterSetup。 我将安装 HDFS 版本 3.3.4，因此我需要 java-8，因为这是 Hadoop 推荐的 Java 版本。
> “我”改成”这里“比较好，下同，‘我们’可以保留

already edited.

2023-03-10 07:19 UTC, xxisxuxu commented on docker/executable_wrapper/HDFS_installation_zh.md
> +这就是 namenode 的配置。 现在对于你需要部署 datanode 的那两个节点，创建一个目录来存储 datanode 运行时数据
> 换行

这里指在哪里换行？@kevinthfang

2023-03-10 07:20 UTC, xxisxuxu commented on docker/executable_wrapper/HDFS_installation_zh.md
> +然后到另外两台datanode机器，到 hadoop 分布，用下面这个命令启动 data node
> ‘分布’改成文件夹下同

already edited.

2023-03-14 07:25 UTC, kevinthfang approved these changes

2023-03-14 07:59 UTC, merged