Create FDB_installation_zh.md
ByConity/ByConity pull request #137
Opened 2023-03-08 04:19 UTC by LorreinMa

I hereby agree to the terms of the CLA available at: [placeholder]

Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...Add Chinses doc FDB_installation

Detailed description / Documentation draft:

...

If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md) guide first.

2023-03-08 04:20 UTC, LorreinMa commented
@kevinthfang pls review

2023-03-08 05:32 UTC, kevinthfang requested changes

2023-03-08 05:32 UTC, kevinthfang commented on docker/executable_wrapper/FDB_installation_zh.md
> +首先，我们需要在[此处](https://github.com/apple/foundationdb/releases/)下载并安装的二进制文件。 我们需要下载**服务器**，**监视器**和**CLI**二进制文件，以及那些coressponding **sha256**校验和文件，本指南选择撰写时的最新版本**7.1.25**版。 接着创建一个文件夹并使用以下命令下载：
Use english names in such cases

2023-03-08 05:32 UTC, kevinthfang commented on docker/executable_wrapper/FDB_installation_zh.md
> +假设您下载它们并存储在目录/`/root/user_xyz/foundationdb/bin`中。 接下来删除那些sha256 checksum文件，因为我们不再需要它们。我们将重命名可执行文件（executation file）以删除Tailting`x86_64` 并授予它们可执行的许可（executable permission）。
可以精简一点，让翻译痕迹不要那么重，比如
假设它们被存储在目录/`/root/user_xyz/foundationdb/bin`中。 接下来可以删除那些sha256 checksum文件，因为不再需要使用。我们可以重命名可执行文件并授予它们可执行的权限。
下同

2023-03-08 05:32 UTC, kevinthfang commented on docker/executable_wrapper/FDB_installation_zh.md
> +然后回到第一台机器，执行这条命令，将冗余模式改为 `triple`
删除这个“将冗余模式改为 `triple`”

2023-03-14 07:23 UTC, kevinthfang approved these changes

2023-03-15 03:45 UTC, merged