support krb5 for hdfs
ByConity/ByConity pull request #194
Opened 2023-03-28 06:29 UTC by white-cc

### Changelog category :
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

add krb5 support for hdfs

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

2023-03-28 06:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ByConity/ByConity?pullRequest=194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ByConity/ByConity?pullRequest=194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ByConity/ByConity?pullRequest=194) it.</sub>

2023-04-02 01:32 UTC, WillemJiang commented
@white-cc Please add the license header [as this](https://github.com/ByConity/ByConity/blob/master/src/DaemonManager/DaemonJobServerBGThread.cpp#L1)  on the files you created.

2023-04-04 11:40 UTC, WillemJiang requested changes

2023-04-04 11:40 UTC, WillemJiang commented on src/Storages/HDFS/HDFSAuth.cpp
> + * Copyright (2022) Bytedance Ltd. and/or its affiliates
Change it to “Copyright 2023 Bytedance Ltd. and/or its affiliates” ， as it is added this year.

2023-04-04 11:40 UTC, WillemJiang commented on src/Access/KerberosInit.cpp
> +/*
We can remove the below lines if we add the  Bytedance Copyright below the ClickHouse one.

2023-04-04 11:40 UTC, WillemJiang commented on src/Access/KerberosInit.cpp
> + * Copyright 2016-2023 ClickHouse, Inc.
You can put the ‘Copyright 2023 Bytedance Ltd. and/or its affiliates.’ below  the  copyright of ClickHouse.

2023-04-17 11:16 UTC, hustnn approved these changes

2023-04-18 05:05 UTC, merged