WIP: Modify CI to use docker-compose
ByConity/ByConity pull request #312
Opened 2023-05-30 10:44 UTC by vivek-debug

### Changelog category :
- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Other
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

2023-06-01 06:19 UTC, canhld94 requested changes

2023-06-01 06:19 UTC, canhld94 commented on docker/local-deploy/.env
> +HADOOP_CONF_DIR=ci_hdfs_conf_path
This should be `/etc/hadoop/conf`. This is the path inside the pod.

2023-06-01 06:19 UTC, canhld94 commented on docker/local-deploy/docker-compose.yml.multiworkers
> +      - /CI/hdfs:${HADOOP_CONF_DIR}:ro
Cannot use `/CI/hdfs` here. The local path to map to pod volume should be a relative path.

2023-06-01 06:20 UTC, canhld94 commented
In addition, the CI docker image shouldn't be build on top of `byconity-builder`. It also doesn't require to install FDB and HDFS.

2023-06-01 06:21 UTC, vivek-debug commented on docker/local-deploy/docker-compose.yml.multiworkers
> +      - /CI/hdfs:${HADOOP_CONF_DIR}:ro
Using relative path also does not work

2023-06-01 06:33 UTC, vivek-debug commented on docker/local-deploy/.env
> +HADOOP_CONF_DIR=ci_hdfs_conf_path
Error still persists even after this change

2023-06-09 07:14 UTC, vivek-debug commented
> In addition, the CI docker image shouldn't be built on top of `byconity-builder`. It also doesn't require to install FDB and HDFS.

Yes this is true. We don't need FDB and HDFS binaries but we still require libraries installed in the byconity builder

2023-06-12 03:01 UTC, hustnn commented on docker/ci-deploy/docker-compose.yml
> +    image: foundationdb/foundationdb:7.1.24
looks like fdb versions are different?

2023-06-12 03:02 UTC, hustnn commented on docker/ci/Dockerfile
>  COPY hadoop-3.3.4.tar.gz /
will the copy be removed later?

2023-06-13 03:48 UTC, vivek-debug commented on docker/ci/Dockerfile
>  COPY hadoop-3.3.4.tar.gz /
yes this will be removed after this MR is merged as we don't want to interrupt current CI runs

2023-06-13 03:54 UTC, vivek-debug commented on docker/ci-deploy/docker-compose.yml
> +    image: foundationdb/foundationdb:7.1.24
I used the docker-compose created by Canh and the CI works well with this version. The manually installed version was 7.1.0. We can remove the old version eventually with hdfs

2023-06-13 04:46 UTC, hustnn approved these changes

2023-06-13 12:10 UTC, merged